import React, { useState,useEffect } from "react";

import Aos from "aos";
import "aos/dist/aos.css"

function TableWeek() {
  useEffect(()=>{
    Aos.init({duration:1500});

  },[])

  return (
    <>
     <p className='text-center text-white h2 my-5'>(Week 45 - from 2022-10-31 to 2022-11-06)</p>
     <div  className='d-flex justify-content-center'>
       
       <table className="table__week" data-aos="fade-down">
      <thead>
        <tr>
          <td>#</td>
          <td>Wallet</td>
          <td>Ganied Respect</td>
        </tr>
      </thead>
      <tbody >
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
       <tr>
          <td>
              1
          </td>
          <td>
            text.ss
          </td>
          <td>
           5458.7777
          </td>
       </tr>
      </tbody>
    </table>
  </div>
    </>
  
  )
}

export default TableWeek